POST http://localhost:3001/api/v1/foods
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "お肉",
    "expirationDate": 1660782998836,
    "comment": "",
    "placeId": 1,
    "categoryId": "10-275"
}

###
GET http://localhost:3001/api/v1/foods
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:3001/api/v1/foods/4
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "お肉2",
    "expirationDate": 1660782998836,
    "comment": "",
    "placeId": 1,
    "categoryId": "10-275"
}

###
DELETE http://localhost:3001/api/v1/foods/3
content-type: application/json
Authorization: Bearer {{token}}
