POST http://localhost:3001/api/v1/foods/1/places
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNjYwNTY0OTU5fQ.N1YLBGlpN3Q-PdSB6AknSQQb2sJzDcQquNjeHJkOm5U

{
    "name": "キッチン"
}

### 
GET http://localhost:3001/api/v1/foods/1/places
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNjYwNTY0OTU5fQ.N1YLBGlpN3Q-PdSB6AknSQQb2sJzDcQquNjeHJkOm5U### 

### 
PUT http://localhost:3001/api/v1/foods/1/places/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNjYwNTY0OTU5fQ.N1YLBGlpN3Q-PdSB6AknSQQb2sJzDcQquNjeHJkOm5U### 

{
    "name": "キッチン改造"
}

###
DELETE http://localhost:3001/api/v1/foods/1/places/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNjYwNTY0OTU5fQ.N1YLBGlpN3Q-PdSB6AknSQQb2sJzDcQquNjeHJkOm5U