POST http://localhost:3001/api/v1/foods/places
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "キッチン"
}

###
GET http://localhost:3001/api/v1/foods/places
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:3001/api/v1/foods/places/4
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "キッチン改造"
}

###
DELETE http://localhost:3001/api/v1/foods/places/6
content-type: application/json
Authorization: Bearer {{token}}
