POST http://localhost:3001/api/v1/users
content-type: application/json

{
    "email": "test2@example.com",
    "password": "password"
}

###
POST http://localhost:3001/api/v1/users/login
content-type: application/json

{
    "email": "test@example.com",
    "password": "password"
}
