import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React,{Component, Dispatch} from 'react'
import {createRoot} from 'react-dom/client'
import axios from 'axios'


const Home: NextPage = () => {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>食材保存場所</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div id={styles.wrap}>
          <h1>食材保存場所</h1>

          <section className={styles.section}>
            <p className={styles.p}>冷蔵庫</p>
            <div className={styles.input}>
              <input className={styles.button} type="button" value="編集" />
              <input className={styles.button} type="button" value="削除" />
            </div>
          </section>

          <section className={styles.section}>
            <p className={styles.p}>冷凍庫</p>
            <div className={styles.input}>
              <input className={styles.button} type="button" value="編集" />
              <input className={styles.button} type="button" value="削除" />
            </div>
          </section>

          <section className={styles.section}>
            <p className={styles.p}>棚</p>
            <div className={styles.input}>
              <input className={styles.button} type="button" value="編集" />
              <input className={styles.button} type="button" value="削除" />
            </div>
          </section>

          <section className={styles.section}>
            <p className={styles.p}>引き出し</p>
            <div className={styles.input}>
              <input className={styles.button} type="button" value="編集" />
              <input className={styles.button} type="button" value="削除" />
            </div>
          </section>
        </div>
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
